apiVersion: v1
kind: Secret
metadata:
  name: kagent-telegram-secret
  namespace: kagent
type: Opaque
stringData:
  TELEGRAM_BOT_TOKEN: "8897366109:AAGC94b9AZ090GuQLEHaPGdDP1zxNAEwa3E"
  TELEGRAM_CHAT_ID: "767992438"
