apiVersion: kagent.dev/v1alpha2
kind: Agent
metadata:
  name: observability-agent
  namespace: kagent
spec:
  declarative:
    modelConfig: default-model-config
    runtime: python
    tools:
    - mcpServer:
        apiGroup: kagent.dev
        kind: RemoteMCPServer
        name: kagent-tool-server
        toolNames:
        - k8s_get_resources
        - k8s_get_available_api_resources
      type: McpServer
    - agent:
        name: promql-agent
      type: Agent
